import "dotenv/config";
import { drizzle } from "drizzle-orm/libsql";
import { createClient } from "@libsql/client";
import { sql } from "drizzle-orm";

const DATABASE_URL = process.env.DATABASE_URL || "file:local.db";

const client = createClient({ url: DATABASE_URL });
const db = drizzle(client);

export const dishes = [
  {
    name: "Couvert",
    nameFr: "Couvert",
    category: "entradas-frias",
    description: "Seleção de pães artesanais, azeitonas e amêndoas tostadas.",
    ingredients: JSON.stringify(["Baguette multigrãos", "Mini pães italianos", "Azeitona verde gordal", "Manteiga Paysan Breton", "Amêndoas tostadas"]),
    allergens: JSON.stringify(["Glúten", "Oleaginosas (amêndoas)", "Leite e derivados"]),
    preparation: "Dispor os pães em uma cestinha ou tábua. Adicionar azeitonas em ramequim pequeno. Servir com manteiga e amêndoas em potinhos separados.",
    curiosity: "Esquentamos os pães na hora e isso leva por volta de 3 minutos no forno. Não adianta pedir na urgência!",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Coeur de Palmier Frais",
    nameFr: "Coeur de Palmier Frais",
    category: "entradas-frias",
    description: "Tirinhas de pupunha fresco com ovo cozido, mini alcachofra e vinagrete de mostarda.",
    ingredients: JSON.stringify(["Palmito pupunha tolete", "Ovo cozido 7min", "Mini alcachofra cozida", "Broto de beterraba", "Vinagrete mostarda de Dijon", "Sal Maldon", "Pimenta-do-reino preta"]),
    allergens: JSON.stringify(["Ovos"]),
    preparation: "Dispor o palmito cortado como um carpaccio no prato de forma harmoniosa e regar com o vinagrete. Colocar o ovo cortado ao meio no centro. Distribuir as mini alcachofras em volta do ovo. Finalizar com sal Maldon, pimenta-do-reino e os brotos de beterraba.",
    curiosity: "Esse prato é um dos preferidos dos proprietários franceses. O ovo cozido com a gema bem cremosa combinam muito bem com o molho e o restante dos ingredientes.",
    imageUrl: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Classic Tomate, Avocat, Concombre et Oignon Doux",
    nameFr: "Classic Tomate, Avocat, Concombre et Oignon Doux",
    category: "entradas-frias",
    description: "Salada fresca de tomate, pepino japonês, avocado e cebola roxa com molho Costes.",
    ingredients: JSON.stringify(["Pepino japonês sem pele e sem semente", "Tomate italiano sem pele", "Avocado", "Cebola roxa", "Molho Costes", "Manjericão basílico", "Azeite extra virgem", "Sal Maldon", "Pimenta-do-reino preta"]),
    allergens: JSON.stringify([]),
    preparation: "Cortar os ingredientes conforme padrão. Temperar o pepino com azeite e sal e deixar repousar por pelo menos 3 minutos. Montar no prato de maneira que os ingredientes se sobreponham e fiquem altos. Finalizar com manjericão, molho Costes, sal Maldon e pimenta-do-reino preta moída na hora.",
    curiosity: "Essa é a entrada mais barata do menu mas uma das mais surpreendentes. O frescor do pepino, associado ao molho bem particular e o frescor do manjericão tornam o prato um sucesso.",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Melon Pastèque Feta",
    nameFr: "Melon Pastèque Feta",
    category: "entradas-frias",
    description: "Cubos de melão, melancia e queijo feta com azeite e azeitonas Kalamata.",
    ingredients: JSON.stringify(["Melão amarelo", "Melão laranja", "Melancia pingo de mel", "Queijo feta", "Azeitona Kalamata", "Pimenta-do-reino preta", "Manjericão basílico", "Azeite extra-virgem"]),
    allergens: JSON.stringify(["Leite de cabra e derivados"]),
    preparation: "Cortar os frutos em cubos iguais. Dispor no prato com o queijo feta. Finalizar com azeitona Kalamata, azeite, pimenta e manjericão.",
    curiosity: "Nossa salada é inspirada na salada grega e leva os 'primos' do pepino (melancia e melão) na composição. Uma combinação surpreendente e refrescante que agrada a maioria dos paladares. O queijo Feta é de origem grega, protegido por denominação de origem (PDO), feito com leite de ovelha ou mistura de ovelha e cabra.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/melon-feta_508c68fa.jpg",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Aubergine Caramélisée Mozza",
    nameFr: "Aubergine Caramélisée Mozza",
    category: "entradas-frias",
    description: "Berinjela assada com tomate confit, mozzarella de búfala e manjericão basílico.",
    ingredients: JSON.stringify(["Berinjela redonda assada com azeite de ervas", "Tomate cereja confit", "Azeite extra virgem", "Sal Maldon", "Pimenta-do-reino preta", "Mozzarella de búfala", "Manjericão basílico"]),
    allergens: JSON.stringify(["Leite e derivados"]),
    preparation: "Dispor a berinjela no centro do prato. Adicionar os tomates confit cortados ao meio, as folhas de manjericão e a mozzarella por cima. Finalizar com azeite, sal Maldon, pimenta-do-reino preta.",
    curiosity: "De inspiração italiana, o grande diferencial desse prato vegetariano é a berinjela utilizada, no caso, a redonda. Ela não tem o amargor peculiar da berinjela comum e é assada lentamente até ficar macia e caramelizada.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/aubergine-mozza_ec3f789b.jpg",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Tomate / Mozza",
    nameFr: "Tomate / Mozza",
    category: "entradas-frias",
    description: "Tomates cereja e sweetgrape amarelo temperados com manjericão e mozzarella de búfala.",
    ingredients: JSON.stringify(["Tomate cereja", "Tomate sweetgrape amarelo", "Azeite extra virgem", "Sal Maldon", "Pimenta-do-reino preta", "Mozzarella de búfala", "Manjericão basílico"]),
    allergens: JSON.stringify(["Leite e derivados"]),
    preparation: "Cortar os tomates ao meio e marinar no azeite com manjericão, sal Maldon e pimenta-do-reino preta moída na hora. Dispor os tomates no prato com a mozzarella ao centro. Finalizar com sal Maldon, pimenta-do-reino e azeite sobre a mozzarella.",
    curiosity: "",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/tomate-mozza_82187ec5.jpg",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Avocado Thon Épicé",
    nameFr: "Avocado Thon Épicé",
    category: "entradas-frias",
    description: "Tartar de atum com avocado, pimenta dedo-de-moça e molho asiático.",
    ingredients: JSON.stringify(["Atum limpo cortado em cubos", "Avocado", "Pimenta dedo-de-moça", "Gengibre", "Asian sauce", "Coentro (talo e folha)", "Cebolinha"]),
    allergens: JSON.stringify(["Peixe", "Soja", "Pode conter glúten"]),
    preparation: "Amassar ligeiramente o avocado e dispor no prato com a ajuda de um aro. Temperar o avocado com um pouco de molho. Colocar o atum em cubos sobre o avocado e temperar com molho Asian Sauce, sal Maldon, pimenta dedo-de-moça, gengibre julienne, talo de coentro, cebolinha laminada. Finalizar com folhas de coentro.",
    curiosity: "",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/tuna-tartare_72ad4b16.jpg",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "New Style Saumon",
    nameFr: "New Style Saumon",
    category: "entradas-frias",
    description: "Lâminas finas de salmão com molho cítrico asiático, óleo de gergelim e flores comestíveis.",
    ingredients: JSON.stringify(["Salmão laminado", "Óleo de gergelim", "Azeite extra virgem", "Molho New Style (dashi, shoyu, suco de yuzu)", "Gengibre", "Ciboulette", "Alho em pó", "Coentro folha", "Mix de gergelim", "Flor comestível (amor-perfeito)"]),
    allergens: JSON.stringify(["Peixe", "Gergelim"]),
    preparation: "Dispor as 8 lâminas de salmão no prato e maçaricar levemente. Regar com o molho e os óleos. Finalizar com gengibre julienne e ciboulette bastonete sobre cada fatia. Salpicar o alho em pó e o mix de gergelim. Colocar as folhas de coentro no centro do prato e finalizar com a flor de amor perfeito.",
    curiosity: "Prato de inspiração japonesa que leva o suco de limão yuzu que é extremamente aromático.",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&h=400&fit=crop",
    price: "",
    isNew: true,
    isPromo: false,
  },
  {
    name: "Carpaccio de Saint-Jacques",
    nameFr: "Carpaccio de Saint-Jacques",
    category: "entradas-frias",
    description: "Lâminas de vieiras frescas com vinagrete de limão, pimenta e flor comestível.",
    ingredients: JSON.stringify(["Vieira em lâminas finas", "Vinagrete de limão", "Pimenta dedo-de-moça", "Gengibre picado", "Ciboulette picada", "Coentro talo", "Sal Maldon", "Pimenta kimchee em pó", "Flor amor-perfeito"]),
    allergens: JSON.stringify(["Frutos do mar"]),
    preparation: "Dispor as vieiras em círculo no prato. Adicionar o vinagrete de limão por cima. Finalizar com pimenta coreana em pó, talos de coentro, ciboulette, gengibre, pimenta dedo-de-moça, sal Maldon e flor comestível.",
    curiosity: "A vieira é um molusco bivalve altamente valorizado na gastronomia internacional. A nossa vem do Canadá, onde um processo de ultracongelamento é feito na embarcação assim que elas são capturadas, garantindo a melhor qualidade possível.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/scallop-carpaccio_e41bf608.jpg",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Laitue Avocat Centolla",
    nameFr: "Laitue Avocat Centolla",
    category: "entradas-frias",
    description: "Mini alface romana com centolla desfiada, avocado laminado e vinagrete.",
    ingredients: JSON.stringify(["Alface romana mini", "Vinagrete citronette", "Avocado laminado", "Centolla cozida desfiada", "Pimenta-do-reino preta", "Folhas de coentro", "Sal Maldon"]),
    allergens: JSON.stringify(["Crustáceos"]),
    preparation: "Dispor a alface aberta no prato. Adicionar centolla e avocado por cima. Finalizar com vinagrete, temperos e ervas.",
    curiosity: "A centolla é um dos crustáceos mais nobres e desejados da gastronomia sul-americana. Seu nome científico é Lithodes santolla, conhecida como king crab ou centolla patagônica. Encontra-se nas águas frias do Oceano Atlântico Sul e Pacífico Sul.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/crab-avocado_f60e770b.jpg",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Foie Gras Frais de Canard",
    nameFr: "Foie Gras Frais de Canard",
    category: "entradas-frias",
    description: "Terrine de Foie Gras de pato temperado com especiarias.",
    ingredients: JSON.stringify(["Foie gras de pato", "5 épices (anis-estrelado, canela, semente de erva-doce, pimenta de Séchuan, cravo)", "Gengibre em pó, sal e açúcar", "Torrada de pão de fermentação natural", "Pimenta-do-reino preta", "Sal Maldon"]),
    allergens: JSON.stringify(["Contém glúten"]),
    preparation: "Dispor a fatia de foie gras no centro do prato. Finalizar com sal Maldon e pimenta-do-reino moída na hora. Servir acompanhado de torrada.",
    curiosity: "O foie gras é um dos ingredientes mais emblemáticos da alta gastronomia francesa, símbolo de luxo, tradição e refinamento. É reconhecido legalmente como 'parte do patrimônio cultural e gastronômico protegido da França'. A prática de engorda do fígado remonta ao Antigo Egito (cerca de 2500 a.C.).",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/foie-gras-URrxZpAyr65EsVc5v8rRuM.webp",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Filet Carpaccio Comme à Venise",
    nameFr: "Filet Carpaccio Comme à Venise",
    category: "entradas-frias",
    description: "Carpaccio de filé mignon com molho clássico de mostarda.",
    ingredients: JSON.stringify(["Filé mignon em fatias finas", "Molho Venise (gema, mostarda de Dijon, mostarda em pó, óleo, azeite, molho inglês, suco de limão, leite, pimenta)", "Avocado laminado", "Sal Maldon"]),
    allergens: JSON.stringify(["Contém ovos e leite"]),
    preparation: "Dispor as fatias de carne no prato. Colocar o molho por cima em formato de 'zig-zag'. Salpicar com sal Maldon.",
    curiosity: "Criado em Veneza, em 1950, no famoso Harry's Bar, pelo chef Giuseppe Cipriani. Foi preparado pela primeira vez para uma condessa chamada Amalia Nani Mocenigo. O nome 'carpaccio' foi uma homenagem ao pintor renascentista Vittore Carpaccio.",
    imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Les Escargots Extraordinaires",
    nameFr: "Les Escargots Extraordinaires",
    category: "entradas-frias",
    description: "Escargots gratinados com manteiga de ervas.",
    ingredients: JSON.stringify(["6 escargots", "Manteiga de Ervas (manteiga, alho, cebola, salsinha, sal e pimenta-do-reino preta)", "Torradinhas de pão de fermentação natural"]),
    allergens: JSON.stringify(["Contém leite"]),
    preparation: "Colocar os escargots nas conchas e cobrir com bastante manteiga de ervas. Pôr na panelinha de louça e levar à salamandra por 8 minutos. Cortar o pão em pequenos triângulos e dar uma leve tostada. Trocar as conchas para uma louça limpa e servir imediatamente.",
    curiosity: "Os escargots são caracóis terrestres comestíveis, considerados uma iguaria tradicional da gastronomia francesa. O consumo de caracóis remonta à Antiguidade: os romanos já os apreciavam. O prato mais emblemático é o Escargots à la Bourguignonne, típico da região da Borgonha.",
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Rigatoni Tomate Basilico",
    nameFr: "Rigatoni Tomate Basilico",
    category: "massas",
    description: "Rigatoni grano duro servido com molho de tomate artesanal e folhas frescas de manjericão.",
    ingredients: JSON.stringify(["Rigatoni grano duro", "Molho de tomate artesanal", "Manjericão basílico fresco", "Azeite extra virgem", "Parmesão ralado finíssimo"]),
    allergens: JSON.stringify(["Glúten"]),
    preparation: "Cozinhar o rigatoni em água salgada até o ponto ideal. Aquecer o molho de tomate em uma frigideira. Acrescentar as folhas de manjericão desfolhadas. Misturar a massa ao molho, acrescentar parmesão ralado. Finalizar com folhas de basílico e servir.",
    curiosity: "Nosso molho de tomate leva 3 tipos de tomate diferentes: pelatti, polpa e extrato. Além disso, usamos alho, cebola e bastante pimenta-do-reino preta. Sempre levar, junto com o prato, um potinho com parmesão ralado.",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Macaronni aux Morilles",
    nameFr: "Macaronni aux Morilles",
    category: "massas",
    description: "Rigatoni grano duro ao molho cremoso de cogumelos morilles.",
    ingredients: JSON.stringify(["Rigatoni grano duro", "Morilles secos", "Base cremosa (fundo de carne + vinho Madeira + vinho do Porto + creme de leite)", "Cerefólio"]),
    allergens: JSON.stringify(["Glúten", "Leite e derivados"]),
    preparation: "Cozinhar o macarrão em água com sal até o ponto. Aquecer o molho, adicionar os morilles hidratados. Misturar o macarrão e finalizar com cerefólio.",
    curiosity: "Os cogumelos Morilles são altamente apreciados na gastronomia por seu sabor e textura únicos. São selvagens, quase nunca cultivados com sucesso comercialmente, o que aumenta seu valor e exclusividade. Possuem sabor profundo, terroso, levemente amadeirado, com notas de nozes.",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Spicy Lobster Pasta",
    nameFr: "Spicy Lobster Pasta",
    category: "massas",
    description: "Spaghetti ao molho picante com lagosta, tomate e ervas frescas.",
    ingredients: JSON.stringify(["Spaghetti", "Lagosta cozida", "Molho de tomate", "Pasta de Pimenta", "Tomate Cereja confit picante", "Manjericão"]),
    allergens: JSON.stringify(["Glúten", "Crustáceos"]),
    preparation: "Cozinhar a massa em água com sal até o ponto ideal. Adicionar o molho de tomate, tomate confit picante e a pasta de pimenta. Adicionar a lagosta pré cozida. Cozinhar a lagosta no molho por 5 minutos. Misturar a massa ao molho. Empratar colocando o spaghetti no centro, os tomates aos lados e a lagosta por cima de tudo. Finalizar com um belo ramo de basílico.",
    curiosity: "Conseguimos fazer esse prato com 'menos pimenta' (sem a pasta de pimenta) e 'sem pimenta' (sem a pasta de pimenta e sem o tomate cereja confit picante).",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/lobster-pasta-Xzv9KuK4jL7xJwMQ86kygG.webp",
    price: "",
    isNew: true,
    isPromo: false,
  },
  {
    name: "Risotto Crevettes",
    nameFr: "Risotto Crevettes",
    category: "massas",
    description: "Risoto cremoso de camarões com toque de parmesão e manjericão.",
    ingredients: JSON.stringify(["Arroz Carnaroli pré-cozido", "Camarão 11/15", "Basílico frito", "Creme de leite", "Caldo de frango", "Manteiga", "Parmesão ralado", "Pimenta-do-reino preta"]),
    allergens: JSON.stringify(["Leite e derivados", "Crustáceos"]),
    preparation: "Colocar o arroz pré-cozido na panela com creme de leite e caldo de frango. Grelhar os camarões. Finalizar o risoto com manteiga, parmesão, sal e pimenta-do-reino preta. Empratar em prato fundo e colocar os camarões grelhados por cima. Finalizar com folhas de basílico frito.",
    curiosity: "Alguns clientes podem observar que não enviamos mais um molho escuro que acompanhava o prato antigamente. Essa medida foi implementada em todas as unidades do L'Avenue por decisão do chef Didier Coly.",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Le Tigre",
    nameFr: "Le Tigre",
    category: "pratos-principais",
    description: "Filé mignon grelhado com molho tailandês da casa, arroz jasmim e ervas frescas.",
    ingredients: JSON.stringify(["Filé mignon (rabo)", "Marinada tigre (molho de ostra, shoyu, alho, conhaque, pimenta)", "Molho tigre (pasta de camarão, molho de peixe, pasta de pimenta, limão, açúcar)", "Pó de arroz jasmin torrado", "Mix tigre (capim limão, gengibre, pimenta, coentro)", "Sal Maldon"]),
    allergens: JSON.stringify(["Contém soja", "Pode conter glúten", "Crustáceos"]),
    preparation: "Grelhar o filé mignon marinado. Servir com arroz jasmim e molho tigre. Finalizar com mix de ervas e coentro.",
    curiosity: "Esse prato tem inspiração na culinária tailandesa. O ponto sugerido para essa carne é ponto para mal passado. Importante frisar com o cliente que esse prato leva coentro e camarão.",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Paillard Poulet",
    nameFr: "Paillard Poulet",
    category: "pratos-principais",
    description: "Frango orgânico grelhado servido com chutney de manga e molho curry.",
    ingredients: JSON.stringify(["Filé de frango orgânico (paillard)", "Sal refinado", "Sal Maldon", "Pimenta-do-reino preta", "Chutney de manga", "Molho curry"]),
    allergens: JSON.stringify(["Contém peixe"]),
    preparation: "Grelhar o frango orgânico. Servir com chutney de manga e molho curry ao lado.",
    curiosity: "De inspiração tailandesa e indiana, esse prato une a picância do curry com o dulçor do chutney de manga. Quando comidos juntos com o frango, a picância diminui e o equilíbrio torna o prato bem saboroso.",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Filet Mignon Sauce Béarnaise",
    nameFr: "Filet Mignon Sauce Béarnaise",
    category: "pratos-principais",
    description: "Filé mignon grelhado com molho béarnaise.",
    ingredients: JSON.stringify(["Filé mignon porcionado (200g)", "Molho béarnaise (gema, manteiga, estragão, salsinha, échalote, vinagre, vinho branco, suco de limão)", "Óleo de girassol", "Manteiga clarificada", "Sal Maldon", "Pimenta-do-reino preta"]),
    allergens: JSON.stringify(["Contém leite e ovos"]),
    preparation: "Grelhar o filé mignon. Servir com molho béarnaise ao lado. Finalizar com sal Maldon e pimenta-do-reino.",
    curiosity: "O molho Béarnaise é um molho clássico da culinária francesa derivado do molho holandês. Foi criado pelo chef Jean-Louis Françoise Collinet, em 1836, no restaurante 'Pavillon Henri IV', em Saint-Germain-en-Laye, perto de Paris.",
    imageUrl: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Saumon Miso",
    nameFr: "Saumon Miso",
    category: "pratos-principais",
    description: "Salmão marinado em missô com laqueado agridoce.",
    ingredients: JSON.stringify(["Salmão porcionado (200g)", "Marinada salmão (mel, shoyu, suco de maçã, azeite)", "Laqueado (missô, shoyu, mirin, açúcar mascavo)", "Gengibre gari", "Mix de gergelim", "Coentro folha", "Limão"]),
    allergens: JSON.stringify(["Contém soja e gergelim"]),
    preparation: "Grelhar o salmão marinado. Aplicar o laqueado. Servir com gengibre gari, gergelim e coentro. Acompanhar com limão.",
    curiosity: "De inspiração japonesa, esse prato combina bem o salgado do missô e o dulçor do laqueado, lembrando vagamente o famoso 'Miso Black Cod' do chef Nobu Matsuhisa. O ponto sugerido do salmão é 'ponto para mal passado'.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/salmon-miso-YFDU4Zp4UJZKp5y7aj2Q6G.webp",
    price: "",
    isNew: true,
    isPromo: false,
  },
  {
    name: "Tom Yam",
    nameFr: "Tom Yam",
    category: "pratos-principais",
    description: "Caldo tailandês aromático com merluza, cogumelos e ervas frescas.",
    ingredients: JSON.stringify(["Mini alcachofra cozida", "Merluza negra (importada do Alasca)", "Molho Tom Yam", "Capim santo", "Pimenta dedo-de-moça", "Gengibre", "Manjericão basílico", "Coentro"]),
    allergens: JSON.stringify(["Contém peixe"]),
    preparation: "Aquecer o caldo Tom Yam. Adicionar a merluza e os vegetais. Finalizar com ervas frescas.",
    curiosity: "O Tom Yam é um famoso molho tailandês, base de uma das sopas mais icônicas da Tailândia. 'Tom' significa 'ferver' e 'Yam' refere-se a uma mistura de ingredientes frescos e ácidos. A merluza negra é importada do Alasca.",
    imageUrl: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Tartare Tradition",
    nameFr: "Tartare Tradition",
    category: "pratos-principais",
    description: "Steak tartare clássico com temperos frescos.",
    ingredients: JSON.stringify(["Cebola picada", "Picles de pepino picado", "Salsinha picada", "Alcaparras picadas", "Molho tartare (gema, mostarda, tabasco, ketchup, molho inglês, óleo)", "Tabasco", "Ciboulette", "Filé mignon (moído na hora)", "Sal Maldon"]),
    allergens: JSON.stringify(["Contém ovos", "Pode conter glúten"]),
    preparation: "Preparar o molho tartare. Moer o filé mignon na hora. Misturar com os ingredientes. Empratar e finalizar.",
    curiosity: "O nome 'Tartare' evoca os Tártaros, povo nômade das estepes da Ásia Central, embora não haja evidências históricas concretas. O prato como é conhecido hoje surgiu na Europa no final do século XIX. O chef Auguste Escoffier ajudou a popularizar e padronizar o Steak Tartare.",
    imageUrl: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Carré d'Agneau",
    nameFr: "Carré d'Agneau",
    category: "pratos-principais",
    description: "Carré de cordeiro grelhado ao ponto, finalizado com molho da casa.",
    ingredients: JSON.stringify(["Carré de cordeiro limpo", "Molho raita (iogurte, menta, tabasco, suco de limão, échalotte)", "Sal refinado", "Sal Maldon", "Pimenta-do-reino preta", "Coentro"]),
    allergens: JSON.stringify(["Contém leite"]),
    preparation: "Grelhar o carré de cordeiro. Servir com molho raita ao lado. Finalizar com coentro e temperos.",
    curiosity: "O Raita é um molho tradicional da culinária indiana, à base de iogurte natural misturado com especiarias e vegetais frescos. É especialmente apreciado pela capacidade de equilibrar pratos condimentados ou picantes.",
    imageUrl: "https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "La Milanaise",
    nameFr: "La Milanaise",
    category: "pratos-principais",
    description: "Milanesa crocante de filé mignon com penne, molho de tomate e parmesão.",
    ingredients: JSON.stringify(["Filé mignon à milanesa", "Limão siciliano", "Molho de tomate", "Parmesão (lascas)", "Rigatoni com molho de tomate"]),
    allergens: JSON.stringify(["Contém glúten, leite e ovos"]),
    preparation: "Fritar a milanesa. Servir com rigatoni ao molho de tomate e lascas de parmesão. Acompanhar com limão siciliano.",
    curiosity: "Originalmente feito com carne de vitela, esse prato foi adaptado para agradar o paladar brasileiro, então usamos o filé mignon. O rigatoni com molho de tomate não é uma guarnição que possa ser trocada — faz parte do prato.",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Magret de Canard",
    nameFr: "Magret de Canard 'Façon Steak au Poivre'",
    category: "pratos-principais",
    description: "Peito de pato grelhado com molho de pimenta e batata frita.",
    ingredients: JSON.stringify(["Peito de pato", "Molho poivre (creme de leite, caldo de carne, pimenta-do-reino preta, conhaque)", "Salsinha", "Pimenta-do-reino preta", "Sal refinado"]),
    allergens: JSON.stringify(["Contém lactose", "Contém pimenta-do-reino preta"]),
    preparation: "Grelhar o peito de pato. Servir com molho poivre e batata frita. Finalizar com salsinha.",
    curiosity: "O ponto sugerido para essa carne é 'ao ponto'. O magret de canard é o peito do pato criado para a produção de foie gras. O termo 'magret' significa 'peito' em occitano, uma língua falada no sudoeste da França.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Lagosta Grelhada",
    nameFr: "Lagosta Grelhada",
    category: "pratos-principais",
    description: "Lagosta grelhada com spicy mayo e limão.",
    ingredients: JSON.stringify(["Lagosta com carapaça", "Spicy mayo (gema, óleo, missô, pasta de pimenta, cebolinha, coentro, suco de limão)", "Limão taiti cortado", "Coentro", "Pimenta-do-reino preta", "Sal Maldon"]),
    allergens: JSON.stringify(["Contém crustáceos e ovos"]),
    preparation: "Grelhar a lagosta. Servir com spicy mayo ao lado e limão. Acompanhar com batatas fritas.",
    curiosity: "A lagosta é servida tradicionalmente com fritas. Caso o cliente queira trocar o acompanhamento, é possível. O molho é muito saboroso e levemente picante, servido à parte.",
    imageUrl: "https://images.unsplash.com/photo-1590759668628-05b0fc34bb70?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Curry Vert Végan",
    nameFr: "Curry Vert Végan",
    category: "pratos-principais",
    description: "Curry verde cremoso à base de vegetais e leite de coco, com arroz de coco e tofu grelhado.",
    ingredients: JSON.stringify(["Quinoa vermelha cozida", "Vagem holandesa", "Mini cenoura", "Mini alcachofra", "Ervilha torta", "Berinjela mini", "Brócolis ninja", "Abobrinha mini", "Mix de gergelim", "Edamame", "Tofu firme", "Molho curry vert", "Coentro", "Arroz de coco", "Amêndoas laminadas"]),
    allergens: JSON.stringify(["Contém soja, gergelim, amêndoas e glúten"]),
    preparation: "Preparar o curry verde com os vegetais. Grelhar o tofu. Servir com arroz de coco. Finalizar com amêndoas, coentro e échalote frita.",
    curiosity: "A inspiração asiática está presente constantemente no cardápio do L'Avenue. O curry verde é originário da Tailândia Central. O nome tailandês 'Gaeng Keow Wan' significa literalmente 'curry verde doce'.",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Club Sandwich",
    nameFr: "Club Sandwich",
    category: "pratos-principais",
    description: "Sanduíche feito no pão de miga com frango, bacon, tomate, alface, mostarda de Dijon e maionese caseira.",
    ingredients: JSON.stringify(["Pão de miga", "Filé de frango orgânico", "Bacon assado", "Mini alface romana", "Tomate sem pele", "Mostarda de Dijon", "Maionese da casa", "Batata frita", "Ketchup à parte"]),
    allergens: JSON.stringify(["Contém glúten e ovos"]),
    preparation: "Montar o sanduíche em camadas. Servir com batatas fritas e ketchup à parte.",
    curiosity: "O Club Sandwich surgiu nos Estados Unidos no final do século XIX, possivelmente no Union Club de Nova York. Rapidamente se popularizou em clubes sociais e hotéis, tornando-se símbolo de refeições leves e elegantes.",
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Pavlova Fruits Rouges",
    nameFr: "Pavlova Fruits Rouges",
    category: "sobremesas",
    description: "Merengue crocante por fora e macio por dentro, servido com chantilly mascarpone e frutas vermelhas frescas.",
    ingredients: JSON.stringify(["Merengue assado pavlova", "Creme chantilly mascarpone", "Morango", "Mirtilo", "Amora", "Coulis de frutas vermelhas", "Hortelã"]),
    allergens: JSON.stringify(["Ovos", "Leite e derivados"]),
    preparation: "Cortar o merengue ao meio e montar com chantilly e coulis. Distribuir as frutas vermelhas sobre o creme. Polvilhar açúcar de confeiteiro. Servir imediatamente.",
    curiosity: "Batizada em homenagem à famosa bailarina russa Anna Pavlova, durante suas turnês pela Austrália e Nova Zelândia na década de 1920. Austrália e Nova Zelândia reivindicam a criação da receita original.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310419663026805564/nqbPgHcq66gHbm7DvWr6Vo/pavlova-RhMDC6rxU4rafDivq3FwoU.webp",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Torta de Maçã",
    nameFr: "Fine aux Pommes",
    category: "sobremesas",
    description: "Torta fina de maçã servida quente, acompanhada de chantilly mascarpone e calda de caramelo.",
    ingredients: JSON.stringify(["Massa folhada", "Açúcar refinado", "Manteiga", "Maçã fuji ou Pink Lady", "Chantilly mascarpone", "Caramelo com flor-de-sal", "Açúcar de confeiteiro"]),
    allergens: JSON.stringify(["Ovos", "Leite e derivados", "Glúten"]),
    preparation: "Aquecer a torta pré-assada no forno seco a 200°C por 3 minutos. Dispor o chantilly e o caramelo em molheiras. Cortar a torta em 4 pedaços. Salpicar açúcar de confeiteiro. Servir imediatamente.",
    curiosity: "A Tarte Fine aux Pommes é uma sobremesa clássica da confeitaria francesa, conhecida por sua simplicidade, leveza e sofisticação. É uma versão refinada e simples da tradicional torta de maçã.",
    imageUrl: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Costes Cracker Cheesecake",
    nameFr: "Costes Cracker Cheesecake",
    category: "sobremesas",
    description: "Cheesecake assado servido com sorvete de mascarpone e finalizado com açúcar de confeiteiro.",
    ingredients: JSON.stringify(["Cheesecake assada", "Sorvete de mascarpone", "Açúcar de confeiteiro"]),
    allergens: JSON.stringify(["Ovos", "Leite e derivados", "Glúten"]),
    preparation: "Dispor o cheesecake no prato. Adicionar uma quenelle de sorvete de mascarpone em cima. Salpicar açúcar de confeiteiro. Servir imediatamente.",
    curiosity: "Uma das sobremesas mais famosas do L'Avenue Paris. A peculiaridade dessa receita é que a massa leva biscoito 'Club Social' na receita, o que dá um leve sabor salgado à preparação.",
    imageUrl: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=600&h=400&fit=crop",
    price: "",
    isNew: true,
    isPromo: false,
  },
  {
    name: "Sorvete de Baunilha",
    nameFr: "Glace Vanille",
    category: "sobremesas",
    description: "Sorvete artesanal de baunilha servido com tuile de amêndoas.",
    ingredients: JSON.stringify(["Sorvete de baunilha (leite, creme de leite, gema, açúcar e fava de baunilha)", "Tuile de amêndoas assada"]),
    allergens: JSON.stringify(["Oleaginosas (amêndoas)", "Glúten", "Leite"]),
    preparation: "Bater a mistura na Pacojet. Servir o sorvete em uma cumbuca gelada. Adicionar a tuile ao lado. Servir imediatamente.",
    curiosity: "O ponto alto desse sorvete é que batemos as porções para cada serviço. Ele é 100% natural e leva pouquíssimo açúcar.",
    imageUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Sorbet de Morango",
    nameFr: "Sorbet Fraises Fraîches Minute",
    category: "sobremesas",
    description: "Sorbet artesanal de morango servido com tuile de amêndoas.",
    ingredients: JSON.stringify(["Sorbet de morango (morango, glucose e açúcar)", "Tuile de amêndoas assada"]),
    allergens: JSON.stringify(["Oleaginosas (amêndoas)", "Glúten"]),
    preparation: "Bater a mistura na Pacojet. Servir o sorbet em uma cumbuca gelada. Adicionar a tuile ao lado. Servir imediatamente.",
    curiosity: "O ponto alto desse sorbet é que batemos as porções para cada serviço. Ele é 100% natural e leva pouquíssimo açúcar.",
    imageUrl: "https://images.unsplash.com/photo-1488900128323-21503983a07e?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Sorbet Mango Passion",
    nameFr: "Sorbet Mango Passion",
    category: "sobremesas",
    description: "Sorbet artesanal de manga e maracujá servido com tuile de amêndoas.",
    ingredients: JSON.stringify(["Sorbet de manga e maracujá (manga, maracujá, glucose e açúcar)", "Tuile de amêndoas assada"]),
    allergens: JSON.stringify(["Oleaginosas (amêndoas)", "Glúten"]),
    preparation: "Bater a mistura na Pacojet. Servir o sorbet em uma cumbuca gelada. Adicionar a tuile ao lado. Servir imediatamente.",
    curiosity: "O ponto alto desse sorbet é que batemos as porções para cada serviço. Ele é 100% natural e leva pouquíssimo açúcar.",
    imageUrl: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Pain Perdu",
    nameFr: "Brioche Perdu Caramel",
    category: "sobremesas",
    description: "Brioche marinado e assado, servido com framboesas frescas, calda de caramelo e açúcar de confeiteiro.",
    ingredients: JSON.stringify(["Brioche marinado com creme de leite e fava de baunilha", "Framboesa", "Caramelo com flor-de-sal", "Açúcar de confeiteiro"]),
    allergens: JSON.stringify(["Ovos", "Leite e derivados", "Glúten"]),
    preparation: "Aquecer o brioche previamente assado no forno a 200 graus por 3 minutos. Riscar o prato com o caramelo salgado e colocar o brioche no meio. Dispor a framboesa sobre o brioche. Finalizar com açúcar de confeiteiro. Servir imediatamente.",
    curiosity: "O Pain Perdu é uma sobremesa clássica francesa, semelhante à 'rabanada' no Brasil ou ao 'french toast' dos Estados Unidos. Traduzido literalmente do francês, significa 'pão perdido' ou 'pão reaproveitado'.",
    imageUrl: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Torta de Chocolate",
    nameFr: "Ah le Moelleux",
    category: "sobremesas",
    description: "Torta cremosa de chocolate servida com chantilly de mascarpone e calda de caramelo.",
    ingredients: JSON.stringify(["Massa de torta de chocolate", "Caramelo com flor-de-sal", "Chantilly de mascarpone"]),
    allergens: JSON.stringify(["Ovos", "Leite e derivados", "NÃO contém glúten"]),
    preparation: "Aquecer a torta no forno microondas por 20 segundos. Salpicar com açúcar de confeiteiro. Colocar o caramelo e o chantilly em molheiras. Servir imediatamente.",
    curiosity: "O verdadeiro moelleux au chocolat foi criado pelo chef Michel Bras em 1981, com 3 estrelas Michelin em Laguiole (França). No Brasil, a sobremesa passou a ser chamada de 'petit gâteau', mas esse nome não existe com esse significado na França.",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Indécente Profiteroles",
    nameFr: "Indécente Profiteroles",
    category: "sobremesas",
    description: "Massa choux recheada com sorvete de baunilha e calda de chocolate.",
    ingredients: JSON.stringify(["Massa choux (farinha, manteiga, leite, ovos, açúcar, sal e água)", "Sorvete de baunilha", "Calda de chocolate"]),
    allergens: JSON.stringify(["Ovos", "Leite e derivados", "NÃO contém glúten"]),
    preparation: "Cortar a massa choux pré-assada e aquecer no forno a 200 graus por 2 minutos. Rechear com sorvete de baunilha. Colocar a calda de chocolate na jarra. Servir imediatamente.",
    curiosity: "Os profiteroles nasceram na França a partir da técnica da pâte à choux, desenvolvida no século XVI e aperfeiçoada no século XIX. Tornaram-se populares com o trabalho do célebre chef Marie-Antoine Carême, considerado um dos pais da alta gastronomia.",
    imageUrl: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
  {
    name: "Fruits Rouges et Chantilly",
    nameFr: "Fruits Rouges et Chantilly",
    category: "sobremesas",
    description: "Frutas vermelhas frescas servidas com chantilly de mascarpone e baunilha.",
    ingredients: JSON.stringify(["Frutas vermelhas (morango, framboesa, amora e mirtilo)", "Chantilly de mascarpone (creme de leite, mascarpone, baunilha e açúcar de confeiteiro)"]),
    allergens: JSON.stringify(["Leite e derivados", "NÃO contém glúten"]),
    preparation: "Colocar as frutas vermelhas no prato de maneira harmoniosa. Colocar o chantilly na molheira. Servir imediatamente.",
    curiosity: "Essa sobremesa é uma das mais caras do menu porque valoriza ingredientes frescos, sazonais e de difícil acesso. O chantilly é feito com baunilha natural, um dos ingredientes mais caros do mundo (mais caro que ouro por grama, dependendo do mercado).",
    imageUrl: "https://images.unsplash.com/photo-1488900128323-21503983a07e?w=600&h=400&fit=crop",
    price: "",
    isNew: false,
    isPromo: false,
  },
];

async function seed() {
  console.log("Checking if dishes table has data...");
  try {
    const existing = await db.execute(sql`SELECT COUNT(*) as count FROM dishes`);
    const count = existing.rows ? existing.rows[0]?.count : (existing[0]?.count || 0);
    if (count > 0) {
      console.log(`Table already has ${count} dishes. Skipping seed.`);
      process.exit(0);
    }
  } catch (err) {
    console.error("DB QUERY ERROR:", err);
    process.exit(1);
  }

  console.log(`Seeding ${dishes.length} dishes...`);
  
  for (const dish of dishes) {
    await db.execute(sql`
      INSERT INTO dishes (name, nameFr, category, description, ingredients, allergens, preparation, curiosity, imageUrl, price, isNew, isPromo)
      VALUES (${dish.name}, ${dish.nameFr}, ${dish.category}, ${dish.description}, ${dish.ingredients}, ${dish.allergens}, ${dish.preparation}, ${dish.curiosity}, ${dish.imageUrl}, ${dish.price}, ${dish.isNew}, ${dish.isPromo})
    `);
    console.log(`  ✓ ${dish.name}`);
  }

  console.log(`\nDone! ${dishes.length} dishes seeded.`);
  process.exit(0);
}

